/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CardCard: typeof import('./../src/components/card/card.vue')['default']
    CardEmpty: typeof import('./../src/components/card/empty.vue')['default']
    CardList: typeof import('./../src/components/card/list.vue')['default']
    GardenEntries: typeof import('./../src/components/garden/entries.vue')['default']
    GardenInfoCard: typeof import('./../src/components/garden/info-card.vue')['default']
    Layout: typeof import('./../src/components/layout/index.vue')['default']
    LayoutNavbar: typeof import('./../src/components/layout/navbar.vue')['default']
    OrderCard: typeof import('./../src/components/order/card.vue')['default']
    OrderEmpty: typeof import('./../src/components/order/empty.vue')['default']
    OrderList: typeof import('./../src/components/order/list.vue')['default']
  }
}
